version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tasko_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasko
    ports:
      - "5432:5432"
    volumes:
      - tasko_postgres_data:/var/lib/postgresql/data

volumes:
  tasko_postgres_data:
